### ISSUE TITLE
Questions about string counting `build_full_strings` 

### ISSUE THREAD

**Issue by Timothyxxx** [ntunlp/LLMSanitize#8]
Hi,

Thanks for this great effort! 
While going through the code, I was confused `build_full_strings` [here](https://github.com/ntunlp/LLMSanitize/blob/468cb026bb710c5aa8594c80ddd19e204429e9cb/llmsanitize/utils/string_utils.py#L49-L59), in comparison with `build_substrings` function where the repetitive string will be accounted into the number. 
So I am confused as to why this didn't happen in `build_full_strings`.

Thanks for the further explanation.

Best,
Tianbao

**Comment by Timothyxxx** [comment]
Hi guys, may I have more information?

**Comment by Ravoxsg** [comment]
Hi @Timothyxxx  

Thanks for your interest in our work and sorry for a late reply.
The reasoning behind this was that for full strings, we just want to check whether a validation string was entirely included in the training set or not. While for substrings, we might be more granular and want to be interested in how many times a substring was seen. But as of the current methods implemented, we do not use the count of times a substring was included.
